version: '3'
services:

  elasticsearch:
    container_name: sprint_7_elasticsearch
    image: elasticsearch:7.7.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  redis:
    container_name: sprint_7_redis
    image: redis
    restart: always
   
  postgres:
    container_name: sprint_7_postgres
    image: postgres:13
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file: ./.env
  
  flask-auth:
    container_name: sprint_7_flask
    environment:
      - DEBUG=0
    build: ./flask_auth
    env_file: ./.env
    depends_on:
      - "redis"
      - "postgres"

  nginx:
    container_name: sprint_7_nginx
    image: nginx:1.19.2
    volumes:
      - ./nginx_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_gateway/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    depends_on:
      - "flask-auth"

volumes:
  db:
  esdata:
