version: '3'
services:
  redis:
    container_name: sprint_6_redis
    image: redis
    restart: always
   
  postgres:
    container_name: sprint_6_postgres
    image: postgres:13
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file: ./.env
  
  flask-auth:
    container_name: sprint_6_flask
    environment:
      - DEBUG=0
    build: ./flask_auth
    env_file: ./.env
    depends_on:
      - "redis"
      - "postgres"

  nginx:
    container_name: sprint_6_nginx
    image: nginx:1.19.2
    volumes:
      - ./nginx_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_gateway/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    depends_on:
      - "flask-auth"

volumes:
  db:
