description: list all roles
consumes:
  - application/json
parameters:
  - name: Authorization
    in: header
    description: an authorization header
    required: true
    type: string
responses:
  '200':
    description: Successful response
  '400':
    description: Not authorized

