"""log_history added

Revision ID: 4a895d7a33df
Revises: 7efbeb9b51ec
Create Date: 2023-03-02 00:35:24.542972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a895d7a33df'
down_revision = '7efbeb9b51ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint('user_role_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_role_role_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_role_role_id_fkey', 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key('user_role_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
